---
Name: ecommerce_second_hand_product
Before: 
  - 'mysite/*'
After:
  - 'framework/*'
  - 'cms/*'
  - 'ecommerce/*'
---

SecondHandProductGroup:
  base_buyable_class: SecondHandProduct

EcommerceDBConfig:
  extensions:
    - SecondHandEcommerceConfigExtension

SecondHandProductGroup:
  sort_options:
    default:
      Title: 'Default Order - (Most Recent)'
      SQL: "\"Created\" DESC"

EcommerceRole:
  admin_role_permission_codes:
    - CMS_ACCESS_SecondHandProductAdmin




---
Only:
  moduleexists: 'grouped-cms-menu'
---
LeftAndMain:
  menu_groups:
    Shop:
      - SecondHandProductAdmin
