---
Name: ecommerce_second_hand_product
Before:
  - '#app/'
After:
  - '#coreconfig'
  - '#cmsextensions'
  - '#ecommerce'
---
Sunnysideup\Ecommerce\Model\Config\EcommerceDBConfig:
  extensions:
    - Sunnysideup\EcommerceSecondHandProduct\Model\SecondHandEcommerceConfigExtension

Sunnysideup\EcommerceSecondHandProduct\SecondHandProductGroup:
  base_buyable_class: Sunnysideup\EcommerceSecondHandProduct\SecondHandProduct
  sort_options:
    default:
      Title: 'Default Order - (Most Recent)'
      SQL: '"ID" DESC'

Sunnysideup\Ecommerce\Model\Extensions\EcommerceRole:
  admin_role_permission_codes:
    - CMS_ACCESS_SecondHandProductAdmin

---
Name: ecommerce_second_hand_product_menu
After:
  - '#coreconfig'
  - '#cmsextensions'
  - '#ecommerce'
  - '#app'
---
SilverStripe\Admin\LeftAndMain:
  menu_groups:
    Shop:
      children:
        - Sunnysideup-EcommerceSecondHandProduct-Cms-SecondHandProductAdmin
