---
Name: ecommerce_second_hand_product
Before:
  - 'app/*'
After:
  - 'framework/*'
  - 'cms/*'
  - 'ecommerce/*'
---
Sunnysideup\Ecommerce\Model\Config\EcommerceDBConfig:
  extensions:
    - Sunnysideup\EcommerceSecondHandProduct\Model\SecondHandEcommerceConfigExtension
Sunnysideup\EcommerceSecondHandProduct\SecondHandProductGroup:
  base_buyable_class: Sunnysideup\EcommerceSecondHandProduct\SecondHandProduct
  sort_options:
    default:
      Title: 'Default Order - (Most Recent)'
      SQL: '"Created" DESC'
Sunnysideup\Ecommerce\Model\Extensions\EcommerceRole:
  admin_role_permission_codes:
    - CMS_ACCESS_SecondHandProductAdmin
---
Only:
  moduleexists: 'grouped-cms-menu'
---
SilverStripe\Admin\LeftAndMain:
  menu_groups:
    Shop:
      - Sunnysideup\EcommerceSecondHandProduct\Cms\SecondHandProductAdmin
