---
Name: ecommerce_second_hand_product_routes
Before:
  - 'app/*'
After:
  - 'framework/*'
  - 'cms/*'
  - 'ecommerce/*'
---
SilverStripe\Control\Director:
  rules:
    secondhandproductlist//$Action/$ID/$OtherID: Sunnysideup\EcommerceSecondHandProduct\Control\ExportSecondHandProducts
    updatesecondhandproduct//$Action/$ID/$OtherID: Sunnysideup\EcommerceSecondHandProduct\Control\UpdateSecondHandProduct
